### ISSUE TITLE
[Question] Build Status for Pull Requests

### ISSUE THREAD

**Issue by gep13** [mendhak/teamcity-stash#22]
I have my TeamCity Server setup to trigger a build when Pull Requests are created in Stash, using:

+:refs/pull-requests/*/merge

Are you expecting that the Build Status from the resulting build should be reported back and displayed "somewhere" in Stash?

Unless I am looking in the wrong place, I don't seem to see this status anywhere.

Thanks!

**Comment by patelnidhice** [comment]
+:refs/heads/* -> I tried this but it gives error. Cant I build same pull request multiple times with this plugin? Only for the first time when build automatically gets triggered after pull request, after that even if I trigger the build manually, I dont see build notification count being incremented on stash. It shows only first build result. Am I missing anything?
