### ISSUE TITLE
how to disable this plugin?

### ISSUE THREAD

**Issue by iwteih** [mendhak/teamcity-stash#25]
I've disabled this plugin in build features, but the build status in TeamCity is still sent to Stash.
Should I restart TeamCity?

**Comment by mendhak** [comment]
Hi you shouldn't have to do that.  Can you try re enabling then re disabling it?  Sounds like TeamCity server acting funny.

**Comment by iwteih** [comment]
Good idea. While it works by deleting the build feature. I will try your option next time.
Btw, teamcity-stash is terrific! Thank you!
