### ISSUE TITLE
Build feature not available in TeamCity 9.1.1

### ISSUE THREAD

**Issue by naderghanbari** [mendhak/teamcity-stash#26]
In TeamCity 9.1.1 I installed the plugin and it show is the list of plugins (plugin name: teamcity.stash) but "Notify Stash.." does not show up in the list of build features. Is it a compatibility problem with 9.1.1?

**Comment by mendhak** [comment]
Currently using 9.1.1 at work with this plugin and also tried a fresh install just to be sure:

![image](https://cloud.githubusercontent.com/assets/746276/9563172/fd3b3b10-4e73-11e5-89ce-ed72366a8672.png)

I'd suggest taking a look at log files if there are any error messages about loading it up.

**Comment by 304NotModified** [comment]
I can confirm the plugin is visible in TeamCity 9.1.5. So it's working.

**Comment by naderghanbari** [comment]
I also upgraded to 9.1.5 and the build feature is visible now.
