### ISSUE TITLE
Implement build trigger for pull request

### ISSUE THREAD

**Issue by Mykolaichenko** [mendhak/teamcity-stash#29]
Its will be very helpful, if you provide the ability to automatically trigger build and report to build status. 
Thanks a lot.

**Comment by mendhak** [comment]
If I understand you correctly - you can get TeamCity to watch a [VCS repo](https://confluence.jetbrains.com/display/TCD9/Configuring+VCS+Triggers) - that should automatically trigger a build.

**Comment by Mykolaichenko** [comment]
@mendhak 
i've speaking about pull request

**Comment by mendhak** [comment]
Sorry, not understanding - even a pull request in Stash/BitBucket will trigger a build

In any case though, this plugin can't do that, it only runs when TC kicks off a build, so it isn't aware of what's already happening in Stash/BitBucket.
